### ISSUE TITLE
No completion of built-in modules

### ISSUE THREAD

**Issue by wbthomason** [EmmyLua/EmmyLua-LanguageServer#13]
I cannot get any completions from built-in modules (e.g. `os`, `io`, etc.). Completion works for tables I define, and most of the rest of the LS functionality works fine, so I don't think I have a configuration error. All that seems to fail is getting completions from these built-in modules. I'm using coc.nvim with the instructions given for EmmyLua-LS here: https://github.com/neoclide/coc.nvim/wiki/Language-servers#lua - am I missing something? Thanks!

**Comment by ZSaberLv0** [comment]
any updates?

I'v found the `stdFolder` option in `LuaLanguageServer.kt`, but it does not work:

```
call coc#config('languageserver.EmmyLua', {
        \   'command': &shell,
        \   'args': [&shellcmdflag, 'java -cp EmmyLua-LS-all.jar com.tang.vscode.MainKt'],
        \   'filetypes': ['lua'],
        \   'initializationOptions': {
        \     'stdFolder': 'path_to_this_repo/std/Lua54',
        \   },
        \ })
```

---

**EDIT:**

* the `stdFolder` is the solution, but you must use `file://` as prefix
* I'v created a repo to make life easier: https://github.com/ZSaberLv0/EmmyLua_stdFolder

**Comment by iqgrande** [comment]
I just wanted to post that I am interested in this as well and would like for the server to handle the built-in modules. I am very appreciative of this project and all of the hard work this team has done. Thank you.

**Comment by ZSaberLv0** [comment]
there's a workaround, copy the contents of https://github.com/EmmyLua/IntelliJ-EmmyLua/tree/master/src/main/resources/std/Lua54 to your project (or to one of your project's sub dir)

but obviously that's not very convenient

**Comment by maximryzhov** [comment]
> any updates?
> 
> I'v found the `stdFolder` option in `LuaLanguageServer.kt`, but it does not work:

You need to specify it as a URI, e.g. 
```
"stdFolder": "file:///C:/EmmyLua-LanguageServer/res/std"
```

**Comment by ZSaberLv0** [comment]
> ```
> "stdFolder": "file:///C:/EmmyLua-LanguageServer/res/std"
> ```

it works!

**Comment by johalun** [comment]
How do I pass stdFolder to emmy in spacemacs on macos?

**Comment by CppCXY** [comment]
use emmylua-analyzer instead of this
