### ISSUE TITLE
modules included by require() in emacs (spacemacs) not seen for autocompletion

### ISSUE THREAD

**Issue by okvorb** [EmmyLua/EmmyLua-LanguageServer#26]
I am not familiar with LSP too much and not quite sure that properly address a problem, but when I use EmmyLua with VSCode then modules included by require() are take place in code autocompletion while emacs does not use included modules for autocompletion.

**Comment by Gliese852** [comment]
@okvorb haven't you solved this problem?

**Comment by okvorb** [comment]
> @okvorb haven't you solved this problem?

Nope

**Comment by CppCXY** [comment]
use emmylua-analyzer instead of this
