### ISSUE TITLE
Can't compile with gradle

### ISSUE THREAD

**Issue by MatanGilead** [EmmyLua/EmmyLua-LanguageServer#3]
Installed JDK and Gradle for this project, getting error:
" What went wrong:
Method com/github/jengelman/gradle/plugins/shadow/internal/DependencyFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract"

Is there an option to compiled jar? (for the current time I just want to run it and not develop it)
thanks

**Comment by tangzx** [comment]
Maybe the incorrect gradle version, The version I'm using is 4.5.
You also can download the jar from [AppVeyor](https://ci.appveyor.com/project/EmmyLua/emmylua-languageserver/build/artifacts)

**Comment by phenix3443** [comment]
@MatanGilead 
you can build with java-8u192, better is use docker, do as follow:
https://phenix3443.github.io/notebook/lua/emmy-lua-ls-all.html
