### ISSUE TITLE
emmyLua with sublime lsp using too much cpu when restart

### ISSUE THREAD

**Issue by XYFFFighting** [EmmyLua/EmmyLua-LanguageServer#34]
I am using emmyLua with sublime lsp and it was awesome, but there is a issue that every time when I restart my sublime, it takes like 5 min to load the project and during the time the cpu usage is almost 100%. Any way to solve this? Thx!

**Comment by CppCXY** [comment]
use other language server such as lua language server

**Comment by CppCXY** [comment]
use emmyluaanalyzer instead of this ls
