### ISSUE TITLE
Feature Request - Diagnostics for Type Errors

### ISSUE THREAD

**Issue by weilbith** [EmmyLua/EmmyLua-LanguageServer#35]
Hey, 

I wonder how hard it would be to add diagnostic support and report type errors. What I would love to see is when I define a function with typed parameter annotation, parameters of calls to this function are checked. Like that: 

```lua
---@param bar number
local function foo(bar)
  print(bar + 1)
end 

foo("bar") -- get diagnistic type error here
```

**Comment by CppCXY** [comment]
Experimental support
