### ISSUE TITLE
现在用eglot的人挺多的，有没有考虑支持一下eglot呀

### ISSUE THREAD

**Issue by a1406** [EmmyLua/EmmyLua-LanguageServer#41]
貌似EmmyLua-LanguageServer只支持lsp-mode吧，eglot下怎么使用EmmyLua-LanguageServer呀，现在用eglot的人挺多的了。

**Comment by CppCXY** [comment]
emmylua语言服务是基于标准的语言服务协议实现的，语言服务客户端是什么倒是无所谓，至于eglot该怎么使用我不清楚，emmyluals的主要开发和使用平台是vscode，或许你可以自己研究一下相关启动参数然后pr到这里来。
